name: xcards
version: 1.0.0+1
publish_to: none

environment:
  sdk: 3.9.2
  flutter: 3.35.6

dependencies:
  auto_route: 10.2.0
  bloc: 9.1.0
  collection: 1.19.1
  envied: 1.3.1
  equatable: 2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: 5.9.3
  flutter_secure_storage: 9.2.4
  freezed: 3.2.3
  freezed_annotation: 3.1.0
  get_it: 8.3.0
  injectable: 2.5.2
  intl: 0.20.2
  json_annotation: ^4.9.0
  retrofit: 4.9.0
  supabase_flutter: 2.10.3

dev_dependencies:
  auto_route_generator: 10.2.5
  bloc_test: 10.0.0
  build_runner: ^2.7.1
  envied_generator: 1.3.1
  flutter_gen_runner: 5.12.0
  flutter_test:
    sdk: flutter
  injectable_generator: 2.8.1
  json_serializable: ^6.8.0
  mocktail: 1.0.4
  retrofit_generator: 10.0.4
  very_good_analysis: 10.0.0

flutter:
  generate: true
  uses-material-design: true
